#!/usr/bin/python

import os
from openboxlogout import openboxlogout
     
if os.path.exists('openbox-logout.conf'):
    config = 'openbox-logout.conf'
else:
    config = None
        
app = openboxlogout.OpenboxLogout(config)
app.run() 
